services:
  optuna-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=optunadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
      
  python:
    image: app
    depends_on:
      - optuna-postgres
    environment: 
      - POSTGRES_DB=optunadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOSTNAME=optuna-postgres

