services:
  optuna-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=optunadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  mlflow-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=mlflowdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5435:5432"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_pass
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio_user minio_pass;
      /usr/bin/mc mb myminio/mlflow;
      exit 0;
      "
volumes:
  minio_data:

# optuna-hp-tuning-app:
#   build: ./app/
#   depends_on:
#     - optuna-postgres
#     - mlflow-postgres
#   environment: 
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=mysecretpassword
#     - POSTGRES_OPTUNA_DB=optunadb
#     - POSTGRES_OPTUNA_HOSTNAME=optuna-postgres
#     - MLFLOW_TRACKING_URI=postgresql+psycopg2://postgres:mysecretpassword@mlflow-postgres:5433/mlflowdb
      